apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 035135759817.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newName: 035135759817.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newTag: aa68ef2e
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
